version: "3"
services:
  web:
    image: myapp:alpine
    deploy:
      replicas: 2
    ports:
    - "3000:3000"
    networks:
      - webnet
    restart_policy:
        condition: on-failure
networks:
  webnet: